<a href="https://colab.research.google.com/github/sumi2426/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np #numerical python
#array collection of datawith same datatype(homogenious)
a=np.array([1,2,3.0,4])
a

array([1., 2., 3., 4.])

In [ ]:
a=np.array([1,2,3.0,4,"a"])
print(a)

['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing- forward slicing,backward slicing

b=np.array([1,2,3,4,5])
#print 1,2
print(b[0:2])
#print 5,4
print(b[-1:-3:-1])
#print 4,5
print(b[3::])
#print 2,1
print(b[-4::-1])


[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimensions

a=np.array([0,2,3,4,5])
b=np.array([[1,2],[3,4]])
a.ndim  #dimension=1 vector
b.ndim  #dimension=2 matrix
print(b)
b.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3
                    #4,5
z=np.array([[2,3],[4,5]])
print(z)
print(z.shape)     #to show 2x2 matrix
print(z.ndim)
print(z.size)      #to show the no: of elements

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print,size,shape,dimension

s=np.array([[1,2,3],[3,4,5]])
print(s)
print(s.size)
print(s.shape)
print(s.ndim)

[[1 2 3]
 [3 4 5]]
6
(2, 3)
2


In [ ]:
#create a 4x2 matrix display its size, shape,dimesions

s=np.array([[1,2],[3,4],[5,6],[7,8]])
print(s)
print(s.size)
print(s.shape)
print(s.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
(4, 2)


In [ ]:
#create a 4x4

a=np.array([[1,2,3,4],[2,5,6,8],[3,7,9,0],[2,6,8,4]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[1 2 3 4]
 [2 5 6 8]
 [3 7 9 0]
 [2 6 8 4]]
2
16
(4, 4)


In [5]:
a=np.arange(1,10).reshape(3,3)
print(a)
a.max(axis=1)
a.max(axis=0)
a.min()
a.min(axis=1)
a.min(axis=0)
a.sum()
a.sum(axis=1)
a.sum(axis=0)
np.sqrt(a)
np.sin(a)
np.cos(a)
np.tan(a)
#flatten= to convert to one dimensional array
a.flatten()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#sort
#create 3x3 matrix
a=np.array([[3,4,1],[4,6,7],[3,6,8]])
a.ndim
print(a)
b=np.sort(a,axis=1)     #0 to sort column wise
b                       #1 to sort row wise
print(b)
c=np.argsort(a,axis=1)  #to show index
print(c)

[[3 4 1]
 [4 6 7]
 [3 6 8]]
[[1 3 4]
 [4 6 7]
 [3 6 8]]
[[2 0 1]
 [0 1 2]
 [0 1 2]]
